@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package creeperbabytea.tealib.registry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;