@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package creeperbabytea.tealib.client.operation;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;